name: Synchronize Labels
"on":
    push:
        branches:
            - main
        paths:
            - .github/labels.yml
jobs:
    synchronize:
        name: Synchronize Labels
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: micnncim/action-label-syncer@v1
              env:
                GITHUB_TOKEN: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
