name: Update Draft Release
"on":
    push:
        branches:
            - main
jobs:
    update:
        name: Update Draft Release
        runs-on:
            - ubuntu-latest
        steps:
            - id: release-drafter
              uses: release-drafter/release-drafter@v5
              env:
                GITHUB_TOKEN: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
            - uses: actions/checkout@v4
            - name: Update draft release with buildpack information
              uses: docker://ghcr.io/paketo-buildpacks/actions/draft-release:main
              with:
                github_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
                release_body: ${{ steps.release-drafter.outputs.body }}
                release_id: ${{ steps.release-drafter.outputs.id }}
                release_name: ${{ steps.release-drafter.outputs.name }}
                release_tag_name: ${{ steps.release-drafter.outputs.tag_name }}
